config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :categories
      resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  devise_for :users
  root 'welcome#index'

  resources :products do
     member do
       post :add_to_cart
     end
     collection do
      get :search
     end
   end

   resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

   resources :cart_items
   resources :orders

   namespace :account do
   resources :orders do
      member do
        post :confirm
        post :pay_with_alipay
        post :pay_with_wechat
        post :apply_to_cancel
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def quantity
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.quantity.present?
        sum += cart_item.quantity
      end
    end
    sum
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

  def clean!
    cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

  def set_payment_with!(method)
    self.update_columns(payment_method: method )
  end

  def pay!
    self.update_columns(is_paid: true )
  end

  belongs_to :user
  has_many :product_lists

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned
    state :confirm


    event :good_job do
      transitions from: :shipped, to: :confirm
    end

    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid,         to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :confirm,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
   belongs_to :category
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin_required
    if !current_user.admin?
      redirect_to "/", alert: "You are not admin."
    end
  end

  helper_method :current_cart

   def current_cart
     @current_cart ||= find_cart
   end

   private

   def find_cart
     cart = Cart.find_by(id: session[:cart_id])
     if cart.blank?
       cart = Cart.create
     end
     session[:cart_id] = cart.id
     return cart
   end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!
  respond_to :js, only: [:decrease, :increase]

  def destroy
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    @product = @cart_item.product
    @cart_item.destroy

    flash[:warning] = "成功将 #{@product.title} 从购物车删除!"
    redirect_to :back
  end

  def update
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    if @cart_item.product.quantity >= cart_item_params[:quantity].to_i
      @cart_item.update(cart_item_params)
      flash[:notice] = "成功变更数量"
    else
      flash[:warning] = "数量不足以加入购物车"
    end

    redirect_to carts_path
  end



  # 增加数量
def increase
  # 加入购物车的数量不能超过库存数量
  if @cart_item.quantity < @cart_item.product.quantity
    @cart_item.change_quantity!(1)
  end
end


# 减少数量
def decrease
  # 课程数量最少为1件
	if @cart_item.quantity > 1
		@cart_item.change_quantity!(-1)
	end
end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clean
    current_cart.clean!
    flash[:warning] = "已清空购物车"
    redirect_to carts_path
  end

  def checkout
    @order = Order.new
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total = current_cart.total_price

    if @order.save

      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order = @order
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.quantity = cart_item.quantity
        product_list.save
      end

      redirect_to order_path(@order.token)
    else
      render 'carts/checkout'
    end
  end

  def show
    @order = Order.find_by_token(params[:id])
    @product_lists = @order.product_lists
  end

  private

  def order_params
    params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]

  def index
    if params[:category].blank?
      @products = Product.all
      @products = @products.paginate(:page => params[:page], :per_page => 8)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(:category_id => @category_id).paginate(:page => params[:page], :per_page => 8)
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
     @product = Product.find(params[:id])

     if !current_cart.products.include?(@product)
       current_cart.add_product_to_cart(@product)
       flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
     else
         flash[:warning] = "你的购物车内已有此物品"
     end
     redirect_to :back
   end

  def search
    if @query_string.present?
      @products = search_params
    end
  end

   protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "")if params[:q].present?
  end


  def search_params
    Product.ransack({:title_or_description_cont => @query_string}).result(distinct: true)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
      @resource ||= User.new
  end

  def resource_class
      User
  end

  def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end

  def render_quantity(cart)
    cart.quantity
  end

end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_paid_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_cart_empty.html.erb
<div class="col-md-12">
  <div class="box-center">
    <p class="empty-pic"></p>
    <h3>购物车还是空的~ </h3>
    <a href="/products" class="btn btn-primary btn-round btn-normal"> 快去挑选商品</a>
  </div>
</div>

app/views/carts/_cart_items.html.erb
<div class="container">

  <div class="cart-title sp-5 sp-6">
  <h2 class="pull-left nomargin"> 我的购物车 </h2>
</br>
</br>
    <span style="margin-left:15px"><i class="fa fa-trash"> </i>
    <%= link_to("清空购物车", clean_carts_path ,
            method: :delete ,
            style: "text-decoration: none",
            data: { confirm: "你确定要清空整个购物车吗？"} )%>
    </span>
  </div>

  <!-- 购物车列表 -->

  <div class="cart_items col-md-9">

      <table class="table table-striped">

        <tbody>

          <% current_cart.cart_items.each do |cart_item| %>
            <tr>
              <td>
                <%= link_to product_path(cart_item.product) do %>
                  <% if cart_item.product.image.present? %>
                    <%= image_tag(cart_item.product.image.thumb.url, class: "img-sx", style:"margin-left:15px; padding:6px") %>
                  <% else %>
                    <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "img-sx", style:"margin-left:15px; padding:6px") %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
              </td>
              <td>
                ￥<%= cart_item.product.price %>
              </td>
              <td>
                <%= form_for cart_item, url: cart_item_path(cart_item.product_id) do |f| %>
                <%= f.select :quantity, 1..cart_item.product.quantity %>
                <%= f.submit "更新", data: { disable_with: "更新中" } , class: "btn-xs btn-default"%>
              <% end %>
              </td>
              <td>
                <!-- <%= link_to cart_item_path(cart_item.product_id), method: :delete do %> -->
                <!-- <i class="fa fa-trash"></i> -->
                  <%= link_to("删除", cart_item_path(cart_item.product_id),
                              :method => :delete, :data => { :confirm => "确定不要这个商品了吗？" },
                              style: "text-decoration: none;",
                              :class => "btn-sm btn-danger") %>
                <!-- <% end %> -->
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>


  </div>

  <!-- 总计 -->

  <div class="total clearfix col-md-3 ">
       <span>
         <h3 ><i class="fa fa-list-alt"></i> · 总计</h3>
          <hr>
         <h4>共 <%= render_quantity(current_cart) %> 件商品</h4>
       </br>
          <h4> 共计 <%= render_cart_total_price(current_cart) %> 元</h4>
       </span>
    <hr>
    <%= link_to("确认购买", checkout_carts_path, method: :post, class: "btn btn-normal btn-primary btn-round") %>
  </div>
</div>

app/views/carts/checkout.html.erb
<div class="container">
  <div class="col-md-12 sp-1">

   <h2> 购物明细 </h2>

   <table class="table table-bordered">
     <thead>
       <tr>
         <th width="80%">商品明细</th>
         <th>单价</th>
         <th>数量</th>
       </tr>
     </thead>
     <tbody>

       <% current_cart.cart_items.each do |cart_item| %>
         <tr>
           <td>
             <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
           </td>
           <td>
             <%= cart_item.product.price %>
           </td>

           <td>
             <%= cart_item.quantity %>
           </td>

         </tr>
       <% end %>

     </tbody>
   </table>

   <div class="total clearfix">
     <span class="pull-right">
       总计 <%= render_cart_total_price(current_cart) %> CNY
     </span>
   </div>

   <hr>

   <h2> 订单资讯 </h2>

   <div class="order-form">

     <%= simple_form_for @order do |f| %>



         <legend> 订购人</legend>
         <div class="form-group col-lg-6">
           <%= f.input :billing_name  %>
         </div>
         <div class="form-group col-lg-6">
           <%= f.input :billing_address  %>
         </div>

         <legend> 收货人</legend>
         <div class="form-group col-lg-6">
          <%= f.input :shipping_name  %>
         </div>
         <div class="form-group col-lg-6">
           <%= f.input :shipping_address  %>
         </div>

       <div class="checkout">
         <%= f.submit "生成订单", class: "btn btn-lg btn-danger pull-right",
                      data: { disable_with: "Submitting..." } %>
       </div>
     <% end %>

   </div>
 </div>

</div>

app/views/carts/index.html.erb
<% if current_cart.products.count !=0 %>
  <%= render "cart_items" %>
<% else %>
  <%= render "cart_empty" %>
<% end %>