config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :categories
      resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  devise_for :users
  root 'welcome#index'

  resources :products do
     member do
       post :add_to_cart
     end
     collection do
      get :search
     end
   end

   resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

   resources :cart_items
   resources :orders

   namespace :account do
   resources :orders do
      member do
        post :confirm
        post :pay_with_alipay
        post :pay_with_wechat
        post :apply_to_cancel
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
   belongs_to :category
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :admin_required

  def index
    @products = Product.all
    @products = @products.paginate(:page => params[:page], :per_page => 4)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
    @product = Product.find(params[:id])
    @product.category_id = params[:category_id]

    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])

    @product.destroy
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image, :category_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]

  def index
    if params[:category].blank?
      @products = Product.all
      @products = @products.paginate(:page => params[:page], :per_page => 8)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(:category_id => @category_id).paginate(:page => params[:page], :per_page => 8)
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
     @product = Product.find(params[:id])

     if !current_cart.products.include?(@product)
       current_cart.add_product_to_cart(@product)
       flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
     else
         flash[:warning] = "你的购物车内已有此物品"
     end
     redirect_to :back
   end

  def search
    if @query_string.present?
      @products = search_params
    end
  end

   protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "")if params[:q].present?
  end


  def search_params
    Product.ransack({:title_or_description_cont => @query_string}).result(distinct: true)
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product_items.html.erb
  <div class="products-search col-lg-3  col-md-3 col-sm-4 col-xs-6 products sp-4 sp-5">


  <!-- 产品页路径 -->
     <!-- <ol class="breadcrumb">
       <li><a href="/products">全部商品</a></li>
       <li class="active"><a herf=""></a></li>
     </ol> -->

  <!-- 产品列表 -->
      <div class="product-grid">
       <%= link_to product_path(product) do %>
         <% if product.image.present? %>
           <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
         <% else %>
           <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
         <% end %>
       <% end %>
        <p class="title nomargin">
          <%= product.title %>
        </p>
        <p class="price">
          ￥ <%= product.price %>
        </p>

      </div>

  </div>

app/views/products/_search_bar.html.erb
<div class="row">
    <%= form_tag search_products_path , :method => :get, :class => "products-search-form" do %>
      <div class="input-group">
        <input type="text" class="form-control search-bar-input" name="q" value="<%= params[:q] %>" placeholder="输入关键词">

        <span class="input-group-btn">
          <button type="submit" class="btn btn-default search-bar-submit">
            <i class="fa fa-search"> </i>
              搜索
          </button>
        </span>
      </div>
    <% end %>
</div>

app/views/products/index.html.erb
<!-- 模块一 分类导航 -->

<div class="container">
  <div class="text-center product-nav">
      <ul class="nav nav-pills">
        <li class="text"><a href='/products'>全部商品</a></li>
        <% Category.all.each do |category| %>
        <li class="text"><%= link_to category.name, products_path(category: category.name), class: "link" %></li>
        <% end %>
      </ul>
  </div>
</div>

<!-- 模块二 产品列表 -->
<div class="container-fluid bg-color3">

<div class="container">
 <div class="col-lg-12  col-md-12  products sp-2 sp-5 ">

  <!-- 产品页路径 -->
     <!-- <ol class="breadcrumb">
       <li><a href="/products">全部商品</a></li>
       <li class="active"><a herf=""></a></li>
     </ol> -->

  <!-- 产品列表 -->
  <!-- <div class="col-md-12 product-list center-block"> -->
    <% @products.each do |product| %>
      <div class=" product-grid col-lg-3  col-md-3 col-sm-4 col-xs-6">
        <%= link_to product_path(product) do %>
          <% if product.image.present? %>
            <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
          <% else %>
            <%= image_tag("http://placehold.it/200x200&text=No-Picture", class: "thumbnail") %>
          <% end %>
        <% end %>
        <p class="title nomargin">
          <%= product.title %>
        </p>
        <p class="price">
          ￥ <%= product.price %>
        </p>
      </div>
    <% end %>
  <!-- </div> -->
  <!-- 分页器 -->

    <div class="col-xs-12 text-center pagination  pagination-sm nomargin">
      <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
    </div>

</div>
</div>
</div>

<!-- 模块三 科学指导 -->
<div class="container ">

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 tips sp-1">
  <h2>不知道怎么选？科学的指导在这里！</h2>
      <div class="row">
        <div class="col-md-4 col-md-offset-1 ">
          <div class="description left">
            <h2> 如何才能保证坐姿正确？ </h2>
            <p>
              正确的坐姿对我们的身体健康至关重要，为了保持良好的坐姿，我们需要坐具、桌子和支架等工具来合理搭配。只有符合人体工程原理的产品才能帮助我们维持舒适。
            </p>
            <a class="btn btn-primary btn-normal btn-round"href="https://v.qq.com/x/page/e0510sl3d2j.html" target="_blank" >
              <i class="fa fa-play"> </i>
               观看影片
            </a>
          </div>
        </div>
        <div class="col-md-6 ">
          <div class="image img-7"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-md-offset-2 col-md-push-4">
          <div class="description right">
            <h2> 如何打造宜人的环境光？ </h2>
            <p>
              好的灯光不仅能缓解眼睛的紧张、劳累，还可以帮助我们长时间保持专注，缓解压力。那如何打造工作空间的灯光环境呢？看看这里的tips吧~
            </p>
            <a class="btn btn-primary btn-normal btn-round"href="https://v.qq.com/x/page/d05100joznn.html" target="_blank" >
              <i class="fa fa-play"> </i>
              观看影片
            </a>
          </div>
        </div>
        <div class="col-md-6 col-md-pull-6">
          <div class="image img-8"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-md-offset-1">
          <div class="description left">
            <h2> 清新的空气如何产生？ </h2>
            <p>
              大自然是世界上最棒的魔法师，它为我们营造了一个非常宜居的环境，那么我们是否能借用大自然的力量让工作空间时刻清新呢？当然！用植物就好了，科学家已经告诉了我们最佳方案。
            </p>
            <a class="btn btn-primary btn-normal btn-round"href="https://v.qq.com/x/page/k0510vjtamt.html" target="_blank" >
              <i class="fa fa-play"> </i>
               观看影片
            </a>
          </div>
        </div>
        <div class="col-md-6">
          <div class="image img-9"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-md-offset-2 col-md-push-4">
          <div class="description right">
            <h2> 整理术从未如此重要 </h2>
            <p>
              整理不仅让空间变得井井有条，“整理术”的思维还能让人拥有更清晰、理性的头脑去应对那些需要被“收拾”的各种事情。所以我们不光是要知道好的收纳工具，对思维的更新也相当重要。
            </p>
            <a class="btn btn-primary btn-normal btn-round"href="/products?category=规整的空间" target="_blank" >
               查看相关商品
            </a>
          </div>
        </div>
        <div class="col-md-6 col-md-pull-6">
          <div class="image img-10"></div>
        </div>
      </div>
</div>
</div>

app/views/products/search.html.erb
<div class="container">
  <div class="search-page sp-4">
      <% if @products.present? %>
        <span style="margin-left:6em">已为您找到<%= @products.count %>个宝贝</span>
          <ul class="productList">
            <%= render :partial => "product_items", :collection => @products, :as => :product %>
          </ul>
      <% else %>
        <div class="col-md-12">
          <div class="box-center">
            <p class="search-empty-pic"></p>
            <h3> 嗯~ 没找到你说的东西，换个关键词试试？ </h3>
            <a href="/products" class="btn btn-primary btn-round btn-normal"> 要不去这儿看看</a>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
<!-- 图片 -->

  <div class="pic-product sp-5 sp-6">
      <% if @product.image.present? %>
        <%= image_tag(@product.image.medium.url, class: "thumbnail") %>
      <% else %>
        <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
      <% end %>
  </div>
  <!-- <div class="col-md-6">
    <h2> <%= @product.title %> </h2>
    <div style="height:100px;">
      <p>
        <%= @product.description %>
      </p>
    </div>
    <div> 数量 : <%= @product.quantity %> </div>
    <div class="product-price"> ￥ <%= @product.price %> </div>
    <div class="pull-right"> -->

<div class="info sp-5 sp-6">

    <div class="intro-text center-block">
      <h3 class="pull-left"><%= @product.title %></h3>
      <br>
      <br>
      <br>
      <br>
      <p>
        <span>售价</span>：<span style="font-size:1.2em; font-weight:600">￥<%= @product.price %></span>
      </p>
      <br>
      <p>
        <span >还剩</span>：<span><%= @product.quantity %></span> 件
      </p>
      <br>

      <p>
        <span >简介</span>：<span><%= @product.description %></span>
      </p>
      <br>
      <p>
        <span style="color:#a91b0c">满99元包邮 七天无理由退货 </span>
      </p>
      <br>
      <br>
      <p>
      <% if @product.quantity > 0 %>
        <%= link_to("加入购物车", add_to_cart_product_path(@product), :method => :post, :class => "btn btn-primary btn-normal") %>
      <% else %>
        <span class="btn btn-default btn-normal disable">已销售一空，无法购买</span>
      <% end %>
      </p>
    </div>
  </div>


</div>