config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :categories
      resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  devise_for :users
  root 'welcome#index'

  resources :products do
     member do
       post :add_to_cart
     end
     collection do
      get :search
     end
   end

   resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

   resources :cart_items
   resources :orders

   namespace :account do
   resources :orders do
      member do
        post :confirm
        post :pay_with_alipay
        post :pay_with_wechat
        post :apply_to_cancel
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def quantity
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.quantity.present?
        sum += cart_item.quantity
      end
    end
    sum
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

  def clean!
    cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

  def set_payment_with!(method)
    self.update_columns(payment_method: method )
  end

  def pay!
    self.update_columns(is_paid: true )
  end

  belongs_to :user
  has_many :product_lists

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned
    state :confirm


    event :good_job do
      transitions from: :shipped, to: :confirm
    end

    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid,         to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :confirm,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
   belongs_to :category
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!
  respond_to :js, only: [:decrease, :increase]

  def destroy
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    @product = @cart_item.product
    @cart_item.destroy

    flash[:warning] = "成功将 #{@product.title} 从购物车删除!"
    redirect_to :back
  end

  def update
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    if @cart_item.product.quantity >= cart_item_params[:quantity].to_i
      @cart_item.update(cart_item_params)
      flash[:notice] = "成功变更数量"
    else
      flash[:warning] = "数量不足以加入购物车"
    end

    redirect_to carts_path
  end



  # 增加数量
def increase
  # 加入购物车的数量不能超过库存数量
  if @cart_item.quantity < @cart_item.product.quantity
    @cart_item.change_quantity!(1)
  end
end


# 减少数量
def decrease
  # 课程数量最少为1件
	if @cart_item.quantity > 1
		@cart_item.change_quantity!(-1)
	end
end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clean
    current_cart.clean!
    flash[:warning] = "已清空购物车"
    redirect_to carts_path
  end

  def checkout
    @order = Order.new
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total = current_cart.total_price

    if @order.save

      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order = @order
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.quantity = cart_item.quantity
        product_list.save
      end

      redirect_to order_path(@order.token)
    else
      render 'carts/checkout'
    end
  end

  def show
    @order = Order.find_by_token(params[:id])
    @product_lists = @order.product_lists
  end

  private

  def order_params
    params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]

  def index
    if params[:category].blank?
      @products = Product.all
      @products = @products.paginate(:page => params[:page], :per_page => 8)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(:category_id => @category_id).paginate(:page => params[:page], :per_page => 8)
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
     @product = Product.find(params[:id])

     if !current_cart.products.include?(@product)
       current_cart.add_product_to_cart(@product)
       flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
     else
         flash[:warning] = "你的购物车内已有此物品"
     end
     redirect_to :back
   end

  def search
    if @query_string.present?
      @products = search_params
    end
  end

   protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "")if params[:q].present?
  end


  def search_params
    Product.ransack({:title_or_description_cont => @query_string}).result(distinct: true)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
      @resource ||= User.new
  end

  def resource_class
      User
  end

  def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end

  def render_quantity(cart)
    cart.quantity
  end

end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_paid_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<!-- <footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Rails101
        <br>Design by wangjingru

    </p>
</footer> -->

<script>
  window.intercomSettings = {
    app_id: "eu5aink1"
  };
</script>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/eu5aink1';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>

<footer>
    <div id="footer">
        <p class="text-footer1">关于我们 <span>|</span> 帮助中心 <span>|</span> 开放平台 <span>|</span> 诚聘英才 <span>|</span> 联系我们 <span>|</span> 网站合作 <span>|</span> 友情链接
        </p>
        <p class="text-footer2">
          <br> Copyright ©2017 Efficiency Space Design by
            <a href="http://ann61-blog.logdown.com" target=_new>王静如</a>|
            <a href="http://garryz-blog.logdown.com/" target=_new>郑家喻</a>
        </p>
    </div>
</footer>

app/views/common/_navbar.html.erb
<div class="col-md-12">
  <nav class="navbar navbar-default navbar-fixed-top" id="navbar"role="navigation">
    <div class="container">
      <!-- 加入小屏幕下的自适应 & 导航条置顶 by 郑家喻 -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-e panded="false">打造空间<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to("全部商品", products_path) %>
              </li>
             <% Category.all.each do |category| %>
               <li>
                <%= link_to(category.name, products_path(category: category.name)) %>
              </li>
            <% end %>
           </ul>
          </li>

          <!-- 下拉菜单式导航 -->
          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li> -->

        </ul>
        <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to carts_path do  %>
                   购物车 <i class="fa fa-shopping-cart"> </i> ( <%= current_cart.products.count %> )
                <% end %>
              </li>
              <li>
                <% if !current_user %>

                <!-- <li><a href="#" data-toggle="modal" data-target="#signup-modal">注册</a></li>
                <li><a href="#" data-toggle="modal" data-target="#login-modal">登录</a></li> -->

                <li><%= link_to("注册", new_user_registration_path) %> </li>
                <li><%= link_to(content_tag(:i, '登录', class: 'fa fa-sign-in'), new_user_session_path) %></li>

               <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Hi!, <%= current_user.email %>
                      <!-- 能否改为用户的注册名？ -->
                      <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <% if current_user.admin? %>
                      <li>
                        <%= link_to("管理上架货品", admin_products_path ) %>
                        <!-- 加上自己的icon  JB 中级魔改指导-->
                      </li>
                    <% end %>
                    <li>
                      <%= link_to(content_tag(:i, "我的订单", class: 'fa fa-check-square-o'), account_orders_path ) %>
                    </li>
                    <li>
                      <%= link_to(content_tag(:i, '退出登录', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %>
                    </li>
                  </ul>
                </li>
              <% end %>
              </li>
          </ul>
          <ul class="navbar-form navbar-right" >
            <div class="form-group">
              <%= render :partial => "products/search_bar" %>
            </div>
          </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <!-- 弹窗 -->


  <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog" role="document">
      <div class="loginmodal-container">
        <button class="close" data-dismiss="modal">×</button>
         <h2 class="login">邮箱登录</h2>
         <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
           <div class="form-inputs">
             <%= f.input :email, required: false, autofocus: true %>
             <%= f.input :password, required: false %>
             <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
           </div>
           <div class="form-actions">
             <%= f.button :submit, "登录" %>
           </div>
         <% end %>
      </div>
    </div>
  </div>

  <div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
      <div class="loginmodal-container">
        <button class="close" data-dismiss="modal">×</button>
        <h2 class="login">新用户注册</h2>
          <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.input :email, required: true, autofocus: true %>
            <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
            <%= f.input :password_confirmation, required: true %>
          </div>
          <div class="form-actions">
              <%= f.button :submit, "立即注册" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JDstore 后台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "common/navbar" %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li> <%= link_to("Products", admin_products_path) %> </li>
          <li> <%= link_to("Orders", admin_orders_path) %> </li>
          <li><%= link_to("Categories", admin_categories_path)%></li>
        </ul>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>效能空间</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container-fluid">
      <div class="row">
          <%= render "common/navbar" %>
        <div class="page-main">
          <%= render "common/flashes" %>
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render "common/footer" %>
  </body>
</html>